// Auto-generated by `npx supabase gen types typescript`
// Do not edit manually. Run `npm run db:types` to regenerate.

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
